export const CATEGORIES = [
  { id: 'electricidad',   emoji: '⚡', name: 'Electricidad' },
  { id: 'plomeria',       emoji: '🔧', name: 'Plomería' },
  { id: 'albanileria',    emoji: '🧱', name: 'Albañilería' },
  { id: 'construccion',   emoji: '🏗️', name: 'Construcción' },
  { id: 'alarma-robo',    emoji: '🚨', name: 'Alarma Robo' },
  { id: 'alarma-incendio',emoji: '🔥', name: 'Alarma Incendio' },
  { id: 'herreria',       emoji: '🔩', name: 'Herrería' },
  { id: 'portones',       emoji: '🚪', name: 'Portones / Cortinas' },
  { id: 'cctv',           emoji: '📷', name: 'CCTV / Cámaras' },
  { id: 'redes',          emoji: '🌐', name: 'Redes' },
  { id: 'telefonia',      emoji: '📞', name: 'Telefonía' },
  { id: 'portero',        emoji: '🔔', name: 'Portero Eléctrico' },
  { id: 'videoportero',   emoji: '📹', name: 'Videoportero' },
  { id: 'gasista',        emoji: '🌡️', name: 'Gasista' },
  { id: 'durlock',        emoji: '🪵', name: 'Durlock' },
  { id: 'carpinteria',    emoji: '🪚', name: 'Carpintería' },
  { id: 'arquitectura',   emoji: '📐', name: 'Arquitectura' },
  { id: 'ing-civil',      emoji: '🏛️', name: 'Ing. Civil' },
  { id: 'electronica',    emoji: '📱', name: 'Electrónica' },
  { id: 'refrigeracion',  emoji: '❄️', name: 'Refrigeración' },
  { id: 'aire-acond',     emoji: '🌡️', name: 'Aire Acond.' },
  { id: 'computacion',    emoji: '💻', name: 'Computación' },
]

export const PROFESSIONALS = [
  {
    id: '1',
    name: 'Ing. Diego Ferrara',
    type: 'Electricista matriculado',
    initials: 'DF',
    avatarBg: '#FEF3C7',
    avatarColor: '#92400E',
    rating: 4.9,
    reviews: 48,
    services: ['Electricidad', 'Portones / Cortinas', 'Alarma Robo'],
    desde: '$12.000',
    verified: true,
    zone: 'Tucumán centro',
    boost: '5x',
    description: 'Electricista matriculado con 12 años de experiencia. Instalaciones industriales y residenciales. Disponible lunes a sábado.',
  },
  {
    id: '2',
    name: 'Carlos Plomería',
    type: 'Gasista y plomero',
    initials: 'CP',
    avatarBg: '#D1FAE5',
    avatarColor: '#065F46',
    rating: 4.7,
    reviews: 31,
    services: ['Plomería', 'Gasista'],
    desde: '$8.500',
    verified: true,
    zone: 'Gran Tucumán',
    boost: '2x',
    description: 'Plomero y gasista habilitado por ENARGAS. Reparaciones urgentes y obras nuevas. Presupuesto sin cargo.',
  },
  {
    id: '3',
    name: 'SegurTec SRL',
    type: 'Empresa de seguridad',
    initials: 'ST',
    avatarBg: '#EEF2FF',
    avatarColor: '#3730A3',
    rating: 4.8,
    reviews: 95,
    services: ['CCTV / Cámaras', 'Alarma Robo', 'Alarma Incendio', 'Videoportero'],
    desde: '$25.000',
    verified: true,
    zone: 'Tucumán y alrededores',
    boost: '10x',
    description: 'Empresa con 8 años en el mercado. Instalamos sistemas Hikvision, Dahua y DSC. Mantenimiento con contrato.',
  },
  {
    id: '4',
    name: 'RedWifi Instalaciones',
    type: 'Técnico en redes',
    initials: 'RW',
    avatarBg: '#FEE2E2',
    avatarColor: '#991B1B',
    rating: 4.6,
    reviews: 22,
    services: ['Redes', 'Telefonía', 'Computación'],
    desde: '$15.000',
    verified: false,
    zone: 'Yerba Buena / Tucumán',
    boost: '1x',
    description: 'Especialista en redes WiFi, cableado estructurado y telefonía IP. Hogares y empresas.',
  },
  {
    id: '5',
    name: 'Arq. Laura Méndez',
    type: 'Arquitecta + Ing. Civil',
    initials: 'LM',
    avatarBg: '#F0FDF4',
    avatarColor: '#14532D',
    rating: 5.0,
    reviews: 17,
    services: ['Arquitectura', 'Ing. Civil', 'Construcción'],
    desde: '$50.000',
    verified: true,
    zone: 'Tucumán capital',
    boost: '2x',
    description: 'Arquitecta con matrícula provincial. Dirección de obra, planos, permisos municipales y construcción en seco.',
  },
  {
    id: '6',
    name: 'FríoCalor HVAC',
    type: 'Climatización',
    initials: 'FC',
    avatarBg: '#EFF6FF',
    avatarColor: '#1E3A8A',
    rating: 4.7,
    reviews: 56,
    services: ['Aire Acond.', 'Refrigeración'],
    desde: '$18.000',
    verified: true,
    zone: 'Gran Tucumán',
    boost: '5x',
    description: 'Técnico en refrigeración y climatización. Instalación, reparación y gas de todos los modelos. Servicio técnico oficial.',
  },
  {
    id: '7',
    name: 'TechPuertas',
    type: 'Automatización',
    initials: 'TP',
    avatarBg: '#FFF7ED',
    avatarColor: '#9A3412',
    rating: 4.5,
    reviews: 29,
    services: ['Portones / Cortinas', 'Herrería'],
    desde: '$20.000',
    verified: true,
    zone: 'Tucumán y alrededores',
    boost: '2x',
    description: 'Instalación y reparación de portones automáticos, cortinas y persianas. Motor CAME, Peccinin y Garen.',
  },
  {
    id: '8',
    name: 'ElectroRepara',
    type: 'Electrónica y computación',
    initials: 'ER',
    avatarBg: '#F5F3FF',
    avatarColor: '#4C1D95',
    rating: 4.4,
    reviews: 41,
    services: ['Electrónica', 'Computación'],
    desde: '$5.000',
    verified: false,
    zone: 'Tucumán centro',
    boost: '1x',
    description: 'Reparación de electrónica del hogar, computadoras, notebooks y celulares. Presupuesto gratis.',
  },
]

export const BOOST_OPTIONS = [
  { x: 1,  label: 'Básico',   desc: '1 pase por día — incluido gratis', price: 0,    priceLabel: 'Gratis' },
  { x: 2,  label: 'Doble',    desc: '2 pases por día — más clientes te ven', price: 1200, priceLabel: '$1.200/día' },
  { x: 5,  label: 'Premium',  desc: '5 pases por día — alta exposición', price: 3500, priceLabel: '$3.500/día' },
  { x: 10, label: 'Máximo',   desc: '10 pases por día — primero en la lista', price: 6000, priceLabel: '$6.000/día' },
]

export const PROVIDER_PLANS = [
  {
    id: 'starter',
    name: 'Starter',
    price: 0,
    priceLabel: 'Gratis',
    period: 'hasta 5 ofertas/mes',
    offers: 5,
    features: [
      { ok: true,  text: '5 ofertas por mes' },
      { ok: true,  text: 'Alcance a todos los técnicos' },
      { ok: false, text: 'Frecuencia extra por día' },
      { ok: false, text: 'Soporte prioritario' },
    ],
    featured: false,
  },
  {
    id: 'pro',
    name: 'Pro',
    price: 14900,
    priceLabel: '$14.900',
    period: 'hasta 10 ofertas/mes',
    offers: 10,
    features: [
      { ok: true,  text: '10 ofertas por mes' },
      { ok: true,  text: 'Alcance a todos los técnicos' },
      { ok: true,  text: 'Frecuencia básica (2x/día)' },
      { ok: false, text: 'Soporte prioritario' },
    ],
    featured: true,
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    price: 39900,
    priceLabel: '$39.900',
    period: 'ofertas ilimitadas',
    offers: 999,
    features: [
      { ok: true, text: 'Ofertas ilimitadas' },
      { ok: true, text: 'Frecuencia máxima (10x/día)' },
      { ok: true, text: 'Destacado en resultados' },
      { ok: true, text: 'Soporte prioritario 24/7' },
    ],
    featured: false,
  },
]

export const MOCK_REQUESTS = [
  { id: '1', icon: '⚡', iconBg: '#FEF3C7', title: 'Instalación tablero eléctrico', location: 'Tucumán centro', client: 'Carlos M.', ago: '2 horas', status: 'pending' },
  { id: '2', icon: '📷', iconBg: '#D1FAE5', title: 'Instalación CCTV 4 cámaras', location: 'Yerba Buena', client: 'María G.', ago: '5 horas', status: 'active' },
  { id: '3', icon: '🚪', iconBg: '#EEF2FF', title: 'Automatización portón corredizo', location: 'Ramos Mejía', client: 'Roberto L.', ago: '1 día', status: 'done' },
  { id: '4', icon: '🔥', iconBg: '#FEE2E2', title: 'Alarma de incendio — Oficina', location: 'Microcentro', client: 'Empresa ABC', ago: '2 días', status: 'done' },
]
